name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Print versions
        run: |
          cargo --version
          rustc --version
          cargo clippy --version
          cargo fmt --version

      - name: Lint
        run: cargo clippy --verbose -- -Dwarnings

      - name: Formatting
        run: cargo fmt --check --verbose

      - name: Build
        run: cargo build --verbose

      - name: Tests
        run: cargo test --verbose
